@startuml

hide <<encounter>>

package "FHIR Workflow" #DDDDDD {
class "Schedule" as class7
class "Slot" as class8

class8 -down-> class7
}

together {
class "no-basis-Appointment" as class1
class "no-basis-AppointmentResponse" as class2
'class "no-basis-Encounter" as class3 <<encounter>>
class2 -up-> class1 : appointment
}

package "FHIR Entities" #DDDDDD {
class "Patient" as class4
class "Practitioner" as class5

class4 -down[hidden]-> class5
'class "Person" as class6
}

'class3 -down-> class1 : reference
class1 -left-> class8

class1 -right-> "FHIR Entities" 
'class2 -left-> "FHIR Entities"
'"FHIR Entities" -left[hidden]-> "FHIR Workflow"

@enduml